version: '3.8'
services:
  nip05-bot:
    image: nip05bot
    hostname: nip05bot
    container_name: nip05bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DENO_ENV=production
    restart: unless-stopped
    networks:
      - nostr-daemon

networks:
  nostr-daemon:
    external: true